name: baybayingo
description: A Flutter project for BaybayinGo
publish_to: 'none' # This is a private project
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Optional: add packages you need
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/BGoLogo.png
  fonts:
    - family: Baybayin
      fonts:
        - asset: assets/fonts/BaybayinSimpleTAWBID.ttf
